#!/usr/bin/env bash

# New exercises are released every day at midnight EST.
TODAY=$(TZ=America/New_York date +%d)
THIS_YEAR=$(TZ=America/New_York date +%Y)

# May include leading zeroes; e.g. 01, 25
PADDED_DAY=$TODAY
# Strip any leading zeroes; e.g. 00 -> 0, 0001 -> 1, 25 -> 25
[[ "$PADDED_DAY" =~ ^0*([0-9]+)$ ]] && DAY=${BASH_REMATCH[1]}

NEW_DIR="${PADDED_DAY}"

if [[ -d "${NEW_DIR}" ]]; then
  echo "Note: directory '${NEW_DIR}' already exists." >&2
fi

# Create the new day's directory and copy the template files
mkdir -p "${NEW_DIR}"
touch "${NEW_DIR}/sample.txt"
touch "${NEW_DIR}/input.txt"


# Download the AoC input file for the day using a saved session cookie
AOC_SESSION=$(cat aoc_session_cookie.txt)
curl --silent -o "${NEW_DIR}/input.txt" "https://adventofcode.com/${THIS_YEAR}/day/${DAY}/input" --cookie "session=${AOC_SESSION}"
